# -*- coding: utf-8 -*-
"""sentimental_analysis_by_using_VANDER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i7qaLG5uWLMcdNAY2L0h3Kk1pPgDOSOR
"""

pip install vaderSentiment

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Create the analyzer object
analyzer = SentimentIntensityAnalyzer()

# Input sentence
sentence = input("Enter a sentence: ")

# Get polarity scores
scores = analyzer.polarity_scores(sentence)

# Extract the compound score
compound = scores['compound']

# Decide sentiment category
if compound >= 0.05:
    sentiment = "Positive 😊"
elif compound <= -0.05:
    sentiment = "Negative 😞"
else:
    sentiment = "Neutral 😐"

print(f"Sentence: {sentence}")
print(f"Sentiment: {sentiment}")
print(f"Detailed Scores: {scores}")